trailing_comma:
    mandatory_comma: true
disabled_rules:
  - identifier_name
opt_in_rules:
  - force_unwrapping
  - implicitly_unwrapped_optional
  - implicit_return
analyzer_rules:
  - explicit_self
  - unused_import
