name: Swift Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: swift build

    - name: Run tests
      run: swift test
