name: Xcode Unit Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-12

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_14.0.1.app

    - name: Xcode version
      run: /usr/bin/xcodebuild -version

    - name: Create iPhone SE Simulator
      run: xcrun simctl create "iPhone SE (1st generation)" "iPhone SE (1st generation)"

    - name: Xcode test on iPhone SE
      run: xcodebuild clean test -scheme MixTeam -destination 'platform=iOS Simulator,name=iPhone SE (1st generation)'
